export interface NewCake {
  id: number;
  slug: string;
  name: string;
  category: string;
  image: string;
  price?: number;
  basePrice?: number;
  baseWeight?: string;
  shortDescription?: string;
  description: string;
  flavorProfile?: string;
  flavorNote?: string;
  notice?: string;
  includes?: string[];
  customizable?: boolean;
  egglessAvailable?: boolean;
  featured?: boolean;
  colorPalette?: string[];
  gallery?: string[];
  [key: string]: any;
}

export const NEW_CAKE_CATALOG: NewCake[] = [
  {
    "id": 1,
    "slug": "sleeping-baby-with-roses",
    "name": "Sleeping Baby with Roses",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/Sleeping Baby with Roses/sleepingbabywithroses.png",
    "price": 500,
    "baseWeight": "Premium Chocolate Sculpture",
    "shortDescription": "Beautiful handcrafted sleeping baby chocolate sculpture decorated with elegant pink roses.",
    "description": "An adorable handcrafted chocolate creation featuring a peacefully sleeping baby wrapped in a textured blanket and decorated with delicate pink roses. Designed with premium detailing and artistic finishing, this chocolate masterpiece is perfect for gifting, baby celebrations, and special occasions.",
    "flavorProfile": "Premium Milk Chocolate",
    "includes": [
      "Handcrafted baby chocolate sculpture",
      "Elegant rose decorations",
      "Premium chocolate finish",
      "Detailed artistic design",
      "Luxury gifting presentation",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 1,
    "slug": "pearl-mini-cake",
    "name": "Pearl",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/pearl/pearl.png",
    "price": 900,
    "shortDescription": "Elegant pearl-textured mini cake with a luxurious velvet finish and modern ring design.",
    "description": "A premium designer mini cake crafted with a rich velvet texture and intricate pearl-inspired detailing. Its sophisticated donut-ring shape and vibrant finish make it perfect for birthdays, celebrations, gifting, and special occasions.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "includes": [
      "Premium designer mini cake",
      "Luxury velvet spray finish",
      "Elegant pearl-textured design",
      "Custom name lettering",
      "Perfect for gifting and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 1,
    "slug": "pillow-cake-bento-box",
    "name": "Pillow Cake in Bento Box",
    "category": "pastries",
    "image": "/assets/cakes/pastries/Pillow/pillow.png",
    "price": 250,
    "baseWeight": "Mini Bento Pastry",
    "shortDescription": "Soft pillow-style mini bento cake with elegant heart detailing, perfect for gifting and surprise treats.",
    "description": "A cute and luxurious pillow-style mini cake served inside a premium bento box. Designed with a soft velvet finish and topped with an elegant white heart accent, this dessert is perfect for birthdays, gifting, date surprises, and sweet celebrations.",
    "flavorProfile": "Customizable",
    "includes": [
      "Mini pillow-shaped pastry cake",
      "Premium bento box packaging",
      "Elegant heart chocolate topper",
      "Luxury velvet spray finish",
      "Gold leaf accents",
      "Custom initial personalization"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 1,
    "slug": "waves-sea-shells",
    "name": "The Waves with Sea Shells",
    "category": "regular",
    "image": "/assets/cakes/regular/The Waves with sea shells/seashells.png",
    "baseWeight": "1 Kg",
    "basePrice": 1250,
    "shortDescription": "Ocean-themed designer cake with edible sea shells and blue wave texture.",
    "description": "Elegant ocean-inspired cake featuring textured blue wave frosting, edible pearls, and handcrafted chocolate sea shells. Perfect for birthdays and special celebrations with a premium artistic finish.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 2,
    "slug": "mermaid-chocolate",
    "name": "Mermaid",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/mermaid/mermaid.png",
    "price": 250,
    "baseWeight": "Premium Chocolate Sculpture",
    "shortDescription": "Cute handcrafted mermaid chocolate sculpture with elegant detailing and pastel finishing.",
    "description": "A beautifully handcrafted mermaid-themed chocolate sculpture designed with intricate detailing, flowing hair, and a soft pastel mermaid tail finish. This premium edible art piece is perfect for gifting, kids' celebrations, themed desserts, and special occasions.",
    "flavorProfile": "Premium Milk Chocolate",
    "includes": [
      "Handcrafted mermaid chocolate sculpture",
      "Detailed artistic finishing",
      "Elegant pastel mermaid tail",
      "Premium chocolate texture",
      "Luxury gifting presentation",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 2,
    "slug": "curved-heart-mini-cake",
    "name": "Curved Heart",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/curvedheart/curvedheart.png",
    "price": 700,
    "shortDescription": "Elegant heart-shaped mini cake with a smooth velvet finish and crystal pearl detailing.",
    "description": "A romantic designer mini cake crafted in a beautiful curved heart shape with a luxurious velvet texture and delicate crystal-style accents. Perfect for anniversaries, birthdays, Valentine’s celebrations, surprises, and gifting.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "includes": [
      "Premium heart-shaped mini cake",
      "Luxury velvet spray finish",
      "Crystal pearl-style detailing",
      "Custom name lettering",
      "Perfect for romantic occasions and gifting"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 2,
    "slug": "red-peru-pastry",
    "name": "Red Peru Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/redperu/redperu.png",
    "price": 180,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Exotic Red Peru pastry with a vibrant tropical center and luxurious velvet finish.",
    "description": "A premium handcrafted pastry inspired by tropical flavors and modern dessert artistry. The Red Peru pastry features a smooth velvet finish with a rich fruity center, creating the perfect balance of sweetness and freshness in every bite.",
    "flavorProfile": "Red Peru (Guava Inspired)",
    "includes": [
      "Single premium pastry",
      "Exotic Red Peru flavor profile",
      "Luxury velvet spray finish",
      "Rich tropical fruit center",
      "Modern designer presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 2,
    "slug": "pillow-cake",
    "name": "Pillow Cake",
    "category": "regular",
    "image": "/assets/cakes/regular/pillow cake/pillowcake.png",
    "baseWeight": "1 Kg",
    "basePrice": 1500,
    "shortDescription": "Elegant pink pillow-style designer cake with pearl detailing and soft velvet finish.",
    "description": "Beautifully crafted pillow-inspired designer cake featuring a luxurious pink velvet texture with delicate pearl accents. Perfect for birthdays, anniversaries, and premium celebrations.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 3,
    "slug": "lotus-chocolate-art",
    "name": "Lotus",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/lotus/lotus.png",
    "price": 1100,
    "baseWeight": "Premium Chocolate Art Piece",
    "shortDescription": "Elegant handcrafted lotus-shaped chocolate sculpture with luxurious layered petal detailing.",
    "description": "A stunning lotus-inspired chocolate masterpiece handcrafted with delicate layered petals and premium finishing. This artistic chocolate creation is designed for gifting, festive celebrations, luxury dessert tables, and special occasions where elegance stands out.",
    "flavorProfile": "Premium White Chocolate",
    "includes": [
      "Handcrafted lotus chocolate sculpture",
      "Intricate layered petal detailing",
      "Luxury artistic presentation",
      "Premium white chocolate finish",
      "Perfect for gifting and décor",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 3,
    "slug": "bento-heart-cake",
    "name": "Bento Heart Cake",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/bentoheart/bentoheart.png",
    "price": 400,
    "shortDescription": "Cute heart-shaped bento cake with a rich velvet finish, perfect for gifting and intimate celebrations.",
    "description": "A charming mini bento cake crafted in a modern heart shape with a luxurious velvet texture and elegant finish. Ideal for birthdays, anniversaries, surprise gifts, Valentine’s celebrations, and special moments with loved ones.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "includes": [
      "Premium heart-shaped bento cake",
      "Luxury velvet spray finish",
      "Compact and elegant presentation",
      "Perfect for gifting and celebrations",
      "Customizable flavors available"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 3,
    "slug": "chocolate-cracker-pastry",
    "name": "Chocolate Cracker Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/chocolate cracker/chocolatecracker.png",
    "price": 160,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Rich Chocolate Cracker pastry with a luxurious velvet finish and indulgent chocolate center.",
    "description": "A premium handcrafted Chocolate Cracker pastry designed for true chocolate lovers. Featuring a smooth velvet coating and a decadent chocolate-filled center, this elegant dessert delivers the perfect balance of texture, richness, and indulgence.",
    "flavorProfile": "Chocolate Cracker",
    "includes": [
      "Single premium pastry",
      "Rich Chocolate Cracker flavor",
      "Luxury velvet spray finish",
      "Decadent chocolate center",
      "Modern rectangular pastry design",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 3,
    "slug": "velvet-heart",
    "name": "Velvet Heart",
    "category": "regular",
    "image": "/assets/cakes/regular/velvet heart/velvetheart.png",
    "baseWeight": "1 Kg",
    "basePrice": 1300,
    "shortDescription": "Luxurious red velvet heart-shaped designer cake with elegant textured detailing.",
    "description": "Premium heart-shaped velvet cake crafted with a rich red finish and artistic textured design. A perfect choice for anniversaries, romantic celebrations, birthdays, and special occasions.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 4,
    "slug": "small-lotus-chocolate",
    "name": "Small Lotus",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/minilotus/minilotus.png",
    "price": 150,
    "baseWeight": "Chocolate Art Piece",
    "shortDescription": "Minimal handcrafted lotus-shaped chocolate delicacy with elegant petal detailing.",
    "description": "A beautifully handcrafted small lotus chocolate creation designed with delicate layered petals and a premium finish. Perfect for gifting, dessert platters, return gifts, festive hampers, or adding a touch of elegance to celebrations.",
    "flavorProfile": "Premium White Chocolate",
    "includes": [
      "Handcrafted lotus chocolate art",
      "Elegant layered petal design",
      "Premium white chocolate finish",
      "Minimal luxury presentation",
      "Perfect for gifting and celebrations",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 4,
    "slug": "bento-star-cake",
    "name": "Bento Star",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/bentostar/bentostar.png",
    "price": 400,
    "shortDescription": "Modern star-shaped bento cake with a vibrant velvet finish and trendy designer look.",
    "description": "A stylish designer bento cake crafted in a unique star-inspired shape with a smooth velvet texture and vibrant gradient finish. Perfect for birthdays, aesthetic celebrations, gifting, and modern dessert tables.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹50 extra.",
    "includes": [
      "Premium designer bento cake",
      "Unique star-inspired shape",
      "Luxury velvet spray finish",
      "Modern gradient color styling",
      "Perfect for gifting and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 4,
    "slug": "pineapple-pastry",
    "name": "Pineapple Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/pineapple/pineapple.png",
    "price": 150,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Light and refreshing Pineapple pastry with a vibrant velvet finish and tropical sweetness.",
    "description": "A soft and elegant Pineapple pastry crafted with a smooth creamy texture and refreshing tropical flavor. Finished with a colorful velvet coating in bright pink, yellow, and white tones, this pastry is perfect for anyone who loves light, fruity desserts with a premium presentation.",
    "flavorProfile": "Pineapple",
    "includes": [
      "Single premium pastry",
      "Refreshing pineapple flavor",
      "Colorful velvet spray finish",
      "Soft creamy texture",
      "Modern swirl pastry design",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 4,
    "slug": "multi-heart",
    "name": "Multi Heart",
    "category": "regular",
    "image": "/assets/cakes/regular/multi heart/multiheart.png",
    "baseWeight": "1 Kg",
    "basePrice": 1100,
    "shortDescription": "Modern multi-heart designer cake with elegant velvet texture and pearl accents.",
    "description": "Beautifully crafted multi-heart shaped designer cake featuring a luxurious pink and gold velvet finish with delicate pearl detailing. Perfect for birthdays, anniversaries, and premium celebrations.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 5,
    "slug": "rocher-ball",
    "name": "Rocher Ball",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/rocherballs/rocherballs.png",
    "price": 40,
    "baseWeight": "Single Chocolate Piece",
    "shortDescription": "Smooth chocolate rocher ball with rich hazelnut flavor and elegant chocolate drizzle.",
    "description": "A delicious handcrafted Rocher Ball made with premium chocolate and crunchy hazelnut goodness. Finished with elegant white chocolate drizzling, this bite-sized delight is perfect for gifting, dessert platters, return gifts, or satisfying your sweet cravings.",
    "flavorProfile": "Chocolate & Hazelnut",
    "includes": [
      "Premium chocolate coating",
      "Rich hazelnut flavor",
      "Elegant white chocolate drizzle",
      "Soft and crunchy texture combination",
      "Perfect bite-sized dessert",
      "Made completely of chocolate & hazelnut"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 5,
    "slug": "bento-round-cake",
    "name": "Bento Round",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/bentoround/bentoround.png",
    "price": 420,
    "shortDescription": "Elegant round bento cake with a smooth velvet finish and romantic heart detailing.",
    "description": "A premium round-shaped bento cake featuring a luxurious velvet texture, delicate crystal accents, and a cute heart topper. Perfect for anniversaries, birthdays, date surprises, gifting, and intimate celebrations.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹50 extra.",
    "includes": [
      "Premium round bento cake",
      "Luxury velvet spray finish",
      "Decorative heart chocolate topper",
      "Elegant crystal-style detailing",
      "Perfect for gifting and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 5,
    "slug": "strawberry-pastry",
    "name": "Strawberry Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/strawberry/strawberry.png",
    "price": 150,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Soft and creamy Strawberry pastry with a modern LOVE-shaped design and elegant velvet finish.",
    "description": "A beautifully crafted Strawberry pastry featuring a stylish LOVE-inspired shape with a smooth velvet coating and rich fruity flavor. This premium pastry combines soft creamy layers with refreshing strawberry sweetness, making it perfect for gifting, celebrations, and dessert cravings.",
    "flavorProfile": "Strawberry",
    "includes": [
      "Single premium pastry",
      "Rich strawberry flavor",
      "LOVE-shaped modern design",
      "Velvet spray finish",
      "Soft creamy texture",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 5,
    "slug": "whirlpool",
    "name": "Whirlpool",
    "category": "regular",
    "image": "/assets/cakes/regular/whirlpool/whirlpool.png",
    "baseWeight": "1 Kg",
    "basePrice": 1000,
    "shortDescription": "Elegant whirlpool-inspired designer cake with luxurious velvet texture and crystal detailing.",
    "description": "Modern spiral designer cake crafted with a stunning yellow and orange velvet finish, enhanced with sparkling crystal accents. Perfect for birthdays, celebrations, and premium occasions with a contemporary artistic touch.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 6,
    "slug": "i-love-you-chocolate-bar",
    "name": "I Love You",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/iloveyou/iloveyou.png",
    "price": 150,
    "baseWeight": "Chocolate Bar",
    "shortDescription": "Cute handcrafted chocolate bar with a romantic 'I Love You' message design.",
    "description": "A beautifully crafted romantic chocolate bar featuring an adorable 'I Love You' design with heart detailing. Made using premium chocolate, this sweet treat is perfect for gifting your loved ones on anniversaries, birthdays, Valentine’s Day, or special moments.",
    "flavorProfile": "Premium White Chocolate",
    "includes": [
      "Handcrafted chocolate message bar",
      "Romantic 'I Love You' design",
      "Heart-shaped detailing",
      "Premium white chocolate finish",
      "Perfect for gifting and celebrations",
      "Made completely of chocolate"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 6,
    "slug": "blueberry-pastry",
    "name": "Blueberry Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/blueberry/blueberry.png",
    "price": 150,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Elegant blueberry pastry with a smooth whirlpool design and rich creamy blueberry flavor.",
    "description": "A premium handcrafted blueberry pastry featuring a stunning whirlpool swirl pattern with a smooth velvet finish. Made with rich blueberry flavor and soft creamy layers, this modern dessert is perfect for sweet cravings, gifting, and special occasions.",
    "flavorProfile": "Blueberry",
    "includes": [
      "Single premium pastry",
      "Rich blueberry flavor",
      "Modern whirlpool swirl design",
      "Velvet spray finish",
      "Soft creamy texture",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 6,
    "slug": "double-heart",
    "name": "Double Heart",
    "category": "regular",
    "image": "/assets/cakes/regular/double heart/doubleheart.png",
    "baseWeight": "1 Kg",
    "basePrice": 1300,
    "shortDescription": "Elegant double-heart designer cake with velvet finish and pearl detailing.",
    "description": "Beautifully crafted twin-heart designer cake featuring a luxurious red velvet texture, crystal accents, and elegant pearl detailing at the center. Perfect for anniversaries, engagements, weddings, and romantic celebrations.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 7,
    "slug": "aquatic-themed-chocolates",
    "name": "Aquatic Themed Chocolates",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/aquatictheme/aquatictheme.png",
    "price": 600,
    "baseWeight": "Chocolate Platter",
    "shortDescription": "Fun aquatic-themed handcrafted chocolates featuring sea creatures and ocean-inspired designs.",
    "description": "Dive into a playful ocean-inspired chocolate collection featuring beautifully handcrafted sea creatures and aquatic elements. This colorful assortment includes dolphins, turtles, fishes, shells, starfishes, and seahorses made entirely from premium chocolate. Perfect for kids’ parties, themed celebrations, gifting, and dessert tables.",
    "flavorProfile": "Premium Chocolate Assortment",
    "includes": [
      "Handcrafted aquatic-themed chocolates",
      "Sea creature and ocean-inspired designs",
      "Colorful premium chocolate finish",
      "Perfect for kids and themed parties",
      "Ideal for gifting and dessert platters",
      "Made completely of chocolate"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 7,
    "slug": "pinata-mini-cake",
    "name": "Pinata",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/pinataa/pinataa.png",
    "price": 800,
    "shortDescription": "Luxury heart-shaped pinata mini cake with velvet finish and crystal droplet detailing.",
    "description": "An elegant heart-shaped mini pinata cake crafted with a premium velvet texture and sparkling crystal-style accents. Designed for special celebrations, surprises, anniversaries, birthdays, and romantic occasions.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "includes": [
      "Premium heart-shaped mini cake",
      "Luxury velvet spray finish",
      "Crystal droplet decoration",
      "Elegant gold board presentation",
      "Perfect for gifting and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 7,
    "slug": "heart-pastry",
    "name": "Heart Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/heart/heart.png",
    "price": 150,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Elegant heart-shaped pastry with a glossy red mirror finish and rich romantic presentation.",
    "description": "A premium handcrafted heart pastry featuring a stunning glossy red mirror glaze with pearl accents. Designed for romantic celebrations and gifting, this dessert combines soft creamy layers with a luxurious presentation that makes every occasion special.",
    "flavorProfile": "Strawberry / Red Velvet Style",
    "includes": [
      "Single premium pastry",
      "Heart-shaped design",
      "Glossy mirror glaze finish",
      "Pearl decoration accents",
      "Soft creamy texture",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 7,
    "slug": "the-waves",
    "name": "The Waves",
    "category": "regular",
    "image": "/assets/cakes/regular/the waves/thewaves.png",
    "baseWeight": "1 Kg",
    "basePrice": 1200,
    "shortDescription": "Minimal ocean-inspired designer cake with elegant blue wave detailing.",
    "description": "Beautifully crafted designer cake featuring soothing blue wave textures with a luxurious velvet finish. Inspired by calm ocean waves, this elegant cake is perfect for birthdays, celebrations, and premium occasions.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 8,
    "slug": "choco-lava",
    "name": "Choco Lava",
    "category": "pastries",
    "image": "/assets/cakes/pastries/chocolava/chocolava.png",
    "price": 80,
    "shortDescription": "Soft and rich chocolate lava cupcake with a molten chocolate center.",
    "description": "Indulge in our delicious Choco Lava pastry featuring a moist chocolate sponge with a gooey molten chocolate center. Freshly baked and perfectly portioned, this dessert is ideal for chocolate lovers craving a warm and decadent treat.",
    "flavorProfile": "Chocolate",
    "includes": [
      "Soft chocolate sponge",
      "Molten chocolate lava center",
      "Freshly baked cupcake-style pastry",
      "Rich cocoa flavor",
      "Perfect single-serve dessert"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 8,
    "slug": "musical-themed-chocolates",
    "name": "Musical Themed Chocolates",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/musicaltheme/musicaltheme.png",
    "price": 400,
    "baseWeight": "Chocolate Platter",
    "shortDescription": "Handcrafted musical-themed chocolates featuring instruments and music symbols.",
    "description": "Celebrate music with this creative collection of handcrafted musical-themed chocolates. Designed with beautiful instruments and musical notes, this premium chocolate assortment is perfect for music lovers, themed parties, birthdays, return gifts, and special celebrations.",
    "flavorProfile": "Premium Milk Chocolate",
    "includes": [
      "Handcrafted musical chocolates",
      "Instrument and music note designs",
      "Premium milk chocolate finish",
      "Perfect for themed celebrations",
      "Ideal for gifting and dessert platters",
      "Made completely of chocolate"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 8,
    "slug": "pillow-cake",
    "name": "Pillow Cake",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/pillow/pillow.png",
    "price": 250,
    "shortDescription": "Soft velvet-finish pillow cake topped with a delicate heart centerpiece.",
    "description": "A beautifully crafted mini pillow cake featuring a luxurious velvet texture and an elegant heart-shaped topper. Its soft cushion-inspired design makes it perfect for romantic occasions, gifting, birthdays, and special celebrations.",
    "includes": [
      "Premium pillow-shaped mini cake",
      "Luxury velvet spray finish",
      "Heart-shaped centerpiece",
      "Elegant handcrafted presentation",
      "Perfect for gifting and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 8,
    "slug": "custard-apple-pastry",
    "name": "Custard Apple Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/custard/custard.png",
    "price": 130,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Unique custard apple inspired pastry with an artistic textured design and creamy fruity flavor.",
    "description": "A beautifully handcrafted pastry inspired by the natural texture of custard apple fruit. Finished with a smooth velvet coating and rich creamy flavor, this premium dessert offers a unique visual appeal along with a soft melt-in-mouth experience.",
    "flavorProfile": "Custard Apple",
    "includes": [
      "Single premium pastry",
      "Rich custard apple flavor",
      "Artistic textured design",
      "Velvet spray finish",
      "Soft creamy texture",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 8,
    "slug": "rose-bouquet",
    "name": "Rose Bouquet",
    "category": "regular",
    "image": "/assets/cakes/regular/rose bouqet/rosebouqet.png",
    "baseWeight": "1 Kg",
    "basePrice": 1300,
    "shortDescription": "Elegant rose bouquet designer cake with luxurious velvet floral detailing.",
    "description": "Beautifully crafted floral designer cake featuring intricate red velvet roses with delicate pearl accents. Inspired by a bouquet of blooming roses, this premium cake is perfect for anniversaries, romantic occasions, birthdays, and celebrations.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 9,
    "slug": "four-milk-chocolate-hearts",
    "name": "Four Milk Chocolate Hearts",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/milkchocolatehearts/milkchocolatehearts.png",
    "price": 50,
    "baseWeight": "4 Piece Chocolate Set",
    "shortDescription": "Cute heart-shaped milk chocolates crafted for gifting and sweet celebrations.",
    "description": "A delightful set of four handcrafted heart-shaped milk chocolates made with smooth and creamy premium chocolate. Perfect for gifting, party favors, Valentine’s Day, anniversaries, or simply sharing sweet moments with loved ones.",
    "flavorProfile": "Milk Chocolate",
    "includes": [
      "4 heart-shaped milk chocolates",
      "Smooth and creamy texture",
      "Premium milk chocolate finish",
      "Perfect for gifting and celebrations",
      "Ideal bite-sized sweet treats",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 9,
    "slug": "bento-pull-the-ribbon-cake",
    "name": "Bento with Pull the Ribbon Trend",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/bentowithpullribbon/bentowithpullribbon.png",
    "price": 700,
    "shortDescription": "Trendy pull-the-ribbon bento cake with luxury velvet finish and romantic detailing.",
    "description": "A modern celebration cake inspired by the viral pull-the-ribbon trend. Designed with a premium velvet texture, elegant chocolate ring topper, delicate floral accents, and romantic decorative elements, this cake creates a memorable surprise experience for special occasions.",
    "flavorNote": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹50 extra.",
    "includes": [
      "Premium pull-the-ribbon bento cake",
      "Luxury velvet spray finish",
      "Chocolate decorative topper",
      "Elegant floral and heart detailing",
      "Perfect for anniversaries and celebrations"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 9,
    "slug": "vanilla-pastry",
    "name": "Vanilla Pastry",
    "category": "pastries",
    "image": "/assets/cakes/pastries/vanilla/vanilla.png",
    "price": 100,
    "baseWeight": "Single Premium Pastry",
    "shortDescription": "Classic vanilla pastry with a floral swirl design and soft creamy texture.",
    "description": "A beautifully handcrafted vanilla pastry featuring an elegant floral-inspired swirl design with a soft velvet finish. Made with rich creamy vanilla flavor and light fluffy layers, this pastry offers a simple yet premium dessert experience perfect for every occasion.",
    "flavorProfile": "Vanilla",
    "includes": [
      "Single premium pastry",
      "Classic vanilla flavor",
      "Floral swirl design",
      "Velvet spray finish",
      "Soft creamy texture",
      "Premium handcrafted presentation"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 9,
    "slug": "corolla",
    "name": "Corolla",
    "category": "regular",
    "image": "/assets/cakes/regular/corolla/corolla.png",
    "baseWeight": "1 Kg",
    "basePrice": 1200,
    "shortDescription": "Elegant modern designer cake with dual-tone velvet finish and spiral detailing.",
    "description": "Beautifully crafted contemporary designer cake featuring a luxurious pink and white velvet texture with elegant spiral patterns. Its minimal yet artistic design makes it perfect for birthdays, celebrations, and premium occasions.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 10,
    "slug": "penguin-chocolate",
    "name": "Penguin",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/whitebird/whitebird.png",
    "price": 200,
    "baseWeight": "1 Chocolate Showpiece",
    "shortDescription": "Adorable handcrafted penguin-shaped chocolate perfect for gifting and celebrations.",
    "description": "A cute handcrafted penguin chocolate made using premium chocolate with fine detailing and a playful finish. Ideal for kids, themed celebrations, return gifts, dessert tables, and chocolate lovers who enjoy unique edible art.",
    "flavorProfile": "Milk & White Chocolate",
    "includes": [
      "1 handcrafted penguin chocolate",
      "Premium milk and white chocolate",
      "Detailed edible chocolate artwork",
      "Perfect for gifting and themed events",
      "Kid-friendly chocolate design",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 10,
    "slug": "sunflower",
    "name": "Sunflower",
    "category": "mini-cakes",
    "image": "/assets/cakes/minicakes/sunflower/sunflower.png",
    "baseWeight": "500 Gm",
    "basePrice": 800,
    "shortDescription": "Elegant sunflower-inspired designer cake with geometric floral detailing.",
    "description": "Beautifully crafted designer cake inspired by sunflower patterns, featuring a luxurious velvet finish with elegant geometric detailing and pearl accents. Perfect for birthdays, intimate celebrations, and premium occasions.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 11,
    "slug": "purse-chocolate",
    "name": "Purse",
    "category": "chocolates",
    "image": "/assets/cakes/chocolates/purse/purse.png",
    "price": 500,
    "baseWeight": "1 Chocolate Showpiece",
    "shortDescription": "Elegant purse-shaped handcrafted chocolate with a luxury designer-inspired finish.",
    "description": "A stylish handbag-inspired chocolate creation handcrafted using premium chocolate with detailed textures and a glossy luxury finish. Perfect for gifting, fashion-themed celebrations, birthdays, dessert tables, and special occasions.",
    "flavorProfile": "Milk & Dark Chocolate",
    "includes": [
      "1 handcrafted purse-shaped chocolate",
      "Premium milk and dark chocolate",
      "Luxury designer-inspired detailing",
      "Perfect for gifting and celebrations",
      "Elegant edible chocolate art",
      "Made completely of chocolate"
    ],
    "customizable": false,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 11,
    "slug": "castle-theme-3-tier-birthday-cake",
    "name": "Castle Theme 3 Tier Birthday Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/Theme/Castle Theme/castletheme.png",
    "shortDescription": "Luxury fairytale-inspired 3 tier birthday cake with carousel topper, butterflies, floral accents, and princess castle theme.",
    "description": "Make celebrations magical with this breathtaking Castle Theme 3 Tier Birthday Cake inspired by fairytale castles and carousel dreams. This premium designer cake features elegant floral detailing, butterfly accents, princess-inspired decor, and a luxurious carousel topper centerpiece. Perfect for grand birthdays, themed parties, and unforgettable celebrations.",
    "includes": [
      "2 Kg Strawberry Layer",
      "1 Kg Pineapple Layer",
      "Raspberry Bento Cake",
      "4 Butterscotch Pastries",
      "Carousel topper",
      "Handcrafted edible flowers",
      "Butterfly accents",
      "Custom name plaques",
      "Character elements"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 12,
    "slug": "boss-baby-theme-cake",
    "name": "Boss Baby Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/boss baby/bossbay.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Boss Baby themed designer cake with blueberry and guava fusion flavor, modern bubble texture, and lotus accents.",
    "description": "Celebrate in style with this adorable Boss Baby Theme Cake featuring a unique fusion of Blueberry and Peru (Guava) flavors. Designed with modern bubble textures, elegant lotus detailing, and handcrafted chocolate elements, this premium themed cake is perfect for first birthdays and kids’ celebrations.",
    "flavorProfile": "Zesty Blueberry paired with the tropical sweetness of Peru (Guava).",
    "includes": [
      "Approx. 1 Kg Round Bubble Cake",
      "Boss Baby themed topper",
      "Modern bubble texture finish",
      "Small lotus decorations",
      "Handcrafted chocolate elements"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 13,
    "slug": "unicorn-theme-cake",
    "name": "Unicorn Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/unicorn/unicorn.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Magical unicorn-themed celebration cake with rainbow accents, bubble texture, and vibrant pastel colors.",
    "description": "Bring magical fairytale vibes to your celebration with this stunning Unicorn Theme Cake. Designed with signature big bubble textures, colorful rainbow accents, adorable unicorn toppers, and vibrant pastel tones, this premium celebration combo is perfect for kids’ birthdays and fantasy-themed parties.",
    "includes": [
      "3-Tier Strawberry Round Cake (Approx. 1 Kg)",
      "Signature Big Bubble textured tier",
      "Unicorn toppers",
      "Rainbow theme decorations",
      "1 Strawberry Bento Cake",
      "5 Decorative elements"
    ],
    "colorPalette": [
      "White",
      "Pink",
      "Vibrant Blue"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 14,
    "slug": "astronaut-themed-cake",
    "name": "Astronaut Themed Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/Astronaut/astronaut.png",
    "baseWeight": "1 Kg",
    "shortDescription": "Space-themed designer cake with astronaut toppers, planets, rocket elements, and galaxy-inspired finish.",
    "description": "Explore the galaxy with this exciting Astronaut Themed Cake designed for space lovers and kids’ birthday celebrations. Crafted in rich Chocolate Cracker flavor, this premium designer cake features astronauts, planets, rockets, UFO elements, and a stunning cosmic-inspired finish for a magical outer-space celebration.",
    "flavorProfile": "Chocolate Cracker",
    "includes": [
      "1 Kg Designer Cake",
      "Astronaut toppers",
      "Rocket and UFO elements",
      "Planet decorations",
      "Galaxy-inspired design",
      "Custom age topper"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 15,
    "slug": "cocomelon-cake",
    "name": "Cocomelon Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/cocomelon/cocomelon.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Colorful Cocomelon-themed birthday cake with edible character print and vibrant chocolate decorations.",
    "description": "Bring joy and musical fun to the celebration with this adorable Cocomelon Cake designed especially for little fans. Crafted in luscious strawberry flavor, this vibrant blue designer cake features edible Cocomelon character prints, colorful chocolate decorations, cloud detailing, and personalized name customization for a magical birthday celebration.",
    "flavorProfile": "Luscious Strawberry",
    "includes": [
      "Approx. 1 Kg Designer Cake",
      "Edible Cocomelon character print",
      "Personalized name tag",
      "Chocolate decorative elements",
      "Cloud and colorful star accents",
      "Fondant-free design"
    ],
    "specialFeature": "100% edible and completely fondant-free using premium chocolate decorative elements.",
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 16,
    "slug": "jungle-theme-cake",
    "name": "Jungle Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/jungle/jungle.png",
    "baseWeight": "Approx. 1.5 Kg",
    "shortDescription": "Cute jungle-themed birthday cake with animal toppers, tropical greenery, and pineapple flavor.",
    "description": "Bring the wild jungle adventure to life with this adorable Jungle Theme Cake designed especially for kids’ birthdays. Crafted in delicious pineapple flavor, this vibrant green designer cake features jungle-inspired decorations, tropical greenery, and cute animal toppers including monkey, elephant, and tiger elements for a fun-filled celebration.",
    "flavorProfile": "Pineapple",
    "includes": [
      "Approx. 1.5 Kg Round Cake",
      "Monkey topper",
      "Elephant and tiger elements",
      "Jungle tree decoration",
      "Tropical grass detailing",
      "4 Chocolate decorative elements"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 17,
    "slug": "sinchan-theme-cake",
    "name": "Sinchan Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/sinchan/sinchan.png",
    "shortDescription": "Fun-filled Shinchan themed designer cake with colorful tiers, cartoon toppers, and premium flavor combination.",
    "description": "Bring laughter and cartoon fun to the celebration with this adorable Sinchan Theme Cake inspired by the iconic Shinchan character. Designed with vibrant colorful tiers, playful decorations, and themed character toppers, this premium celebration cake is perfect for kids’ birthdays and cartoon-themed parties.",
    "flavorProfile": "Chocolate Cracker, Strawberry & Peru (Guava)",
    "includes": [
      "Approx. 2 Kg Round Cake",
      "1 Kg Stone Design Tier",
      "Shinchan themed toppers",
      "Character decorations",
      "4 Chocolate decorative elements",
      "Colorful celebration accents"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 18,
    "slug": "cricket-theme-cake",
    "name": "Cricket Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/cricket/cricket.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Cricket-themed designer cake with jersey topper, cricket ball decorations, and stadium-inspired design.",
    "description": "Celebrate the love for cricket with this exciting Cricket Theme Cake designed for sports enthusiasts and birthday celebrations. Crafted in delicious pineapple flavor, this premium designer cake features a cricket jersey topper, cricket ball decorations, bat elements, and a stadium-inspired green field design for the ultimate cricket fan experience.",
    "flavorProfile": "Pineapple",
    "includes": [
      "Approx. 1 Kg Round Cake",
      "Tornado textured design",
      "Cricket jersey topper",
      "Cricket ball and bat elements",
      "Stadium-inspired decorations",
      "4 Custom image elements"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 19,
    "slug": "tom-and-jerry-theme-cake",
    "name": "Tom & Jerry Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/tom and jerry/tomandjerry.png",
    "baseWeight": "Approx. 1.5 Kg",
    "shortDescription": "Fun Tom & Jerry themed designer cake with colorful edible character print and vibrant celebration design.",
    "description": "Bring classic cartoon fun to your celebration with this adorable Tom & Jerry Theme Cake. Crafted in rich Chocolate Cracker flavor, this premium designer cake features vibrant dual-color tiers, colorful star accents, and an edible Tom & Jerry chocolate print topper perfect for kids’ birthdays and cartoon-themed celebrations.",
    "flavorProfile": "Chocolate Cracker",
    "includes": [
      "Approx. 1.5 Kg Designer Cake",
      "Tom & Jerry edible chocolate print",
      "Dual-color celebration tiers",
      "Colorful star decorations",
      "Premium themed finish"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 20,
    "slug": "doremon-theme-cake",
    "name": "Doremon Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/doremon/doremon.png",
    "baseWeight": "Small Cake",
    "shortDescription": "Cute Doremon themed blueberry cake with vibrant blue finish and premium chocolate character topper.",
    "description": "An adorable Doremon Theme Cake specially crafted for cartoon lovers and kids’ celebrations. Designed in a rich blueberry flavor with a smooth vibrant blue finish, this cake features a premium edible Doremon chocolate element that makes birthdays extra fun and memorable.",
    "flavorProfile": "Blueberry",
    "includes": [
      "Small Theme Cake",
      "1 Premium Doremon chocolate element",
      "Blueberry flavor",
      "Custom name decoration",
      "Smooth designer finish"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": false
  },
  {
    "id": 21,
    "slug": "spiderman-theme-cake",
    "name": "Spiderman Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/spiderman/spiderman.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Action-packed Spiderman themed cake with superhero chocolate toppers and city skyline design.",
    "description": "A perfect superhero celebration cake for Marvel and Spiderman fans. Designed with vibrant red and blue tones, detailed web styling, and premium chocolate Spiderman and city skyline elements, this cake brings comic-inspired excitement to birthdays and kids’ parties.",
    "flavorProfile": "Chocolate Cracker",
    "includes": [
      "Approx. 1 Kg Theme Cake",
      "Spiderman chocolate topper",
      "City skyline chocolate element",
      "Spider web design",
      "Custom name decoration"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 22,
    "slug": "football-theme-cake",
    "name": "Football Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/football/football.png",
    "baseWeight": "Approx. 2 Kg",
    "shortDescription": "Premium football themed designer cake with Ronaldo-inspired edible elements and rich chocolate flavors.",
    "description": "Celebrate the love for football with this stunning Football Theme Cake featuring premium edible football-inspired elements, iconic player styling, club logos, and sports-themed decorations. Crafted with luxurious Chocolate Cracker and Dutch Truffle flavors, this cake is perfect for football fans, sports birthdays, and themed celebrations.",
    "flavorProfile": "Chocolate Cracker & Dutch Truffle",
    "includes": [
      "Approx. 1 Kg Chocolate Cracker Cake",
      "Approx. 1 Kg Dutch Truffle Cake",
      "6 Football-themed edible elements",
      "Ronaldo-inspired topper",
      "Football and club logo decorations",
      "Custom name decoration"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 23,
    "slug": "princess-theme-cake",
    "name": "Princess Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/theme-cakes/princess/princess.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Elegant princess themed pearl cake with royal character toppers and dreamy purple-pink finish.",
    "description": "A magical Princess Theme Cake designed to make birthdays feel like a royal celebration. Featuring a beautiful pearl-textured top tier, premium princess elements, butterfly accents, and a soft purple-pink color palette, this cake is perfect for kids who love fairytale and princess-themed parties.",
    "flavorProfile": "Customizable Flavors Available",
    "includes": [
      "Approx. 1 Kg Designer Cake",
      "Pearl-textured top tier",
      "Princess character elements",
      "Castle birthday topper",
      "Butterfly decorations",
      "Custom name decoration"
    ],
    "notice": "All chocolate-based flavors (like Chocolate Cracker, Dutch Truffle, etc.) cost ₹100 extra.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 24,
    "slug": "engagement-heart-cake",
    "name": "Engagement Cake",
    "category": "engagement-cakes",
    "image": "/assets/cakes/Enagement/cake1/cake1.png",
    "baseWeight": "Approx. 2 Kg",
    "shortDescription": "Elegant 2-tier engagement cake featuring a curved heart topper with soft pink romantic aesthetics.",
    "description": "A beautifully designed engagement celebration cake crafted with soft romantic pink shades, pearl detailing, and a premium curved heart topper. This elegant 2-tier cake combines Pineapple and Strawberry flavors, making it perfect for engagements, anniversaries, proposals, and special couple celebrations.",
    "flavorProfile": "Pineapple & Strawberry",
    "includes": [
      "Approx. 1 Kg Pineapple Cake",
      "Curved Heart Strawberry Cake",
      "2-tier designer setup",
      "Pearl decoration accents",
      "Premium romantic finish"
    ],
    "notice": "Customization available for colors, names, and flavors.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 25,
    "slug": "classic-engagement-cake",
    "name": "Engagement Cake",
    "category": "engagement-cakes",
    "image": "/assets/cakes/Enagement/cake2/cake2.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Elegant engagement cake with romantic rose decorations, couple topper, and chocolate ring accents.",
    "description": "A luxurious engagement celebration cake crafted with elegant white finishing, romantic red roses, pearl detailing, and premium engagement-themed decorations. Featuring vanilla flavor, chocolate rings, heart accents, and a graceful couple topper, this cake is perfect for engagements, anniversaries, proposals, and couple celebrations.",
    "flavorProfile": "Vanilla",
    "includes": [
      "Approx. 1 Kg Vanilla Cake",
      "2 Vanilla heart decorations",
      "Chocolate engagement rings",
      "Elegant couple topper",
      "6-7 decorative roses",
      "Pearl detailing"
    ],
    "notice": "Customization available for names, colors, flowers, and flavors.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 26,
    "slug": "anniversary-theme-cake",
    "name": "Anniversary Theme Cake",
    "category": "engagement-cakes",
    "image": "/assets/cakes/Enagement/cake3/cake3.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Romantic Dutch Truffle anniversary cake with heart pastries, couple topper, and fresh pink roses.",
    "description": "Celebrate love and togetherness with this luxurious Dutch Truffle Romance Cake. Crafted with rich silky chocolate truffle flavor, this elegant anniversary cake features handcrafted heart pastries, premium chocolate ring decorations, a romantic couple topper, and beautiful fresh pink roses for a dreamy celebration setup.",
    "flavorProfile": "Dutch Truffle",
    "includes": [
      "Approx. 1 Kg Dutch Truffle Cake",
      "Two Heart pastries",
      "Chocolate ring decorations",
      "Romantic couple topper",
      "Fresh pink roses",
      "Premium anniversary styling"
    ],
    "notice": "Final price may vary depending on the daily market rate of fresh roses.",
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 27,
    "slug": "3-tier-customized-birthday-cake",
    "name": "3 Tier Customized Birthday Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/Theme/3tiercustomized/3tiercustomized.png",
    "baseWeight": "Approx. 2 Kg",
    "shortDescription": "Luxury 3-tier customized birthday cake with Chocolate Cracker, Dutch Truffle rose heart, and Strawberry velvet heart layers.",
    "description": "Make celebrations unforgettable with this stunning 3-tier customized birthday cake featuring premium designer textures and elegant heart-shaped tiers. Crafted with a combination of rich Chocolate Cracker, silky Dutch Truffle, and fruity Strawberry flavors, this masterpiece is perfect for birthdays, surprise celebrations, and luxury occasions.",
    "flavorProfile": "Chocolate Cracker, Dutch Truffle & Strawberry",
    "includes": [
      "Approx. 1 Kg Chocolate Cracker base tier",
      "Rose Heart layer in Dutch Truffle flavor",
      "Velvet Heart layer in Strawberry flavor",
      "Total Approx. 2 Kg cake",
      "Luxury velvet spray finish",
      "Pearl border detailing",
      "Custom name personalization"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 28,
    "slug": "2-tier-customized-birthday-cake",
    "name": "2 Tier Customized Birthday Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/Theme/2tiercustomized/2tiercustomized.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Elegant 2-tier strawberry birthday cake with whirlpool design and heart bundle topper.",
    "description": "A dreamy customized birthday cake crafted in beautiful shades of pink with a luxurious velvet finish. This elegant 2-tier creation features a signature whirlpool top layer crowned with a charming bundle of hearts and golden butterfly accent, making it perfect for birthdays, surprise celebrations, and special moments.",
    "flavorProfile": "Strawberry",
    "includes": [
      "Approx. 1 Kg customized cake",
      "Signature Whirlpool top layer",
      "Small bundle of hearts topper",
      "Golden butterfly decorative accent",
      "Luxury velvet spray finish",
      "Pearl border detailing",
      "Custom name personalization"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 29,
    "slug": "50th-birthday-celebration-theme-cake",
    "name": "50th Birthday Celebration Theme Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/Theme/50thcelebration/50thcelebration.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Elegant 50th birthday celebration cake with Honey Rose flavor, tornado finish, lotus topper, and premium chocolate elements.",
    "description": "Celebrate a golden milestone with this beautifully designed 50th birthday theme cake featuring a luxurious tornado texture and vibrant artistic elements. Crafted in a delightful Honey Rose flavor, the cake is decorated with elegant lotus detailing, cultural accents, and premium handcrafted chocolate elements for a truly memorable celebration.",
    "flavorProfile": "Honey Rose",
    "includes": [
      "Approx. 1 Kg round cake",
      "Signature tornado texture finish",
      "Honey Rose flavor",
      "Golden lotus centerpiece",
      "50 years celebration topper",
      "7 handcrafted chocolate elements",
      "Luxury velvet spray finish",
      "Custom name personalization"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  },
  {
    "id": 30,
    "slug": "car-themed-cake",
    "name": "Car Themed Cake",
    "category": "theme-cakes",
    "image": "/assets/cakes/Theme/car/car.png",
    "baseWeight": "Approx. 1 Kg",
    "shortDescription": "Luxury car themed birthday cake in rich Chocolate Cracker flavor with premium edible car topper.",
    "description": "Perfect for automobile lovers and little car enthusiasts, this stylish car themed cake features a sleek designer finish with an edible luxury car element on top. Crafted in our signature Chocolate Cracker flavor and finished with elegant pearl detailing, this cake makes birthdays and celebrations extra special.",
    "flavorProfile": "Chocolate Cracker",
    "includes": [
      "Approx. 1 Kg round cake",
      "Premium edible car topper",
      "Rich Chocolate Cracker flavor",
      "Luxury velvet spray finish",
      "Pearl decorative accents",
      "Custom name personalization"
    ],
    "customizable": true,
    "egglessAvailable": true,
    "featured": true
  }
];
